### ISSUE TITLE
Issue during  execution

### ISSUE THREAD

**Issue by rkreshch** [tdunning/k-means-auto-encoder#3]
Hello I have an issue with your script

C:\master>Rscript clustering.r
[1] 10
[1] 20
[1] 50
[1] 100
[1] 200
[1] 500
[1] 1000
[1] 2000
null device
          1
null device
          1
Error in is.data.frame(data) : objet 'x' introuvable
Calls: cube.root.fig ... <Anonymous> -> model.frame.default -> is.data.frame
Exécution arrêtée

Please help me to run it.

**Comment by rkreshch** [comment]
Here is a trace

 Hide Traceback
 
 Rerun with Debug
 Error in is.data.frame(data) : object 'x' not found 
11. is.data.frame(data) 
10. model.frame.default(formula = inv ~ rootK, data = x[1:4, ], drop.unused.levels = TRUE) 
9. stats::model.frame(formula = inv ~ rootK, data = x[1:4, ], drop.unused.levels = TRUE) 
8. eval(mf, parent.frame()) 
7. eval(mf, parent.frame()) 
6. lm(inv ~ rootK, x[1:4, ]) at clustering.r#118
5. cube.root.fig() at clustering.r#135
4. eval(ei, envir) 
3. eval(ei, envir) 
2. withVisible(eval(ei, envir)) 
1. source("C:/Python_on_Laptop/R/k-means-auto-encoder-master/k-means-auto-encoder-master/clustering.r")

**Comment by tdunning** [comment]
Check the version I just pushed today.  I think if fixed just that problem.

**Comment by tdunning** [comment]
@rkreshch is this fixed for you?

**Comment by rkreshch** [comment]
Yes, thank you , all works fine !!

2017-05-16 6:51 GMT+02:00 Ted Dunning <notifications@github.com>:
